### ISSUE TITLE
[Bug]: webui command returns invalid url

### ISSUE THREAD

**Issue by MCgrant360** [spartacus04/jext-reborn#255]
### Describe the bug

When running the jextwebui command, the returned url looks like "https://spartacus04.github.io/jext.reborn/?c=c&ip=127.0.0.1&port=9871", but that url returns a 404 error. the given url should look like "https://spartacus04.github.io/jext-reborn/?c=c&ip=127.0.0.1&port=9871" instead.

### Steps to reproduce

1. Start a server with JEXT Reborn installed. 2. Run the /jextwebui command in game or jextwebui from the console. 3. Copy and paste the given url into an internet browser. 

### Expected behaviour

The url will take you to the password screen on the generator, not a 404 error page.

### Server Version

1.20.1

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hello, thanks for the bug report, I've just fixed this in [77b843f](https://github.com/spartacus04/jext-reborn/commit/77b843f4620ebb73ac9ab6b341805182c6c43ab6).

**Comment by MonstaDash** [comment]
Using the latest version, the 404 error still seems to be not fixed

**Comment by spartacus04** [comment]
Yeah, I haven't published it yet since I'm waiting to fix the generator connection problems
