### ISSUE TITLE
[Bug]: can't add disc

### ISSUE THREAD

**Issue by SharisHyT** [spartacus04/jext-reborn#344]
### Describe the bug

How fix that?

### Steps to reproduce

1. Used app 2. Connect to server 3. Added disc

### Expected behaviour

idk

### Logs

[20:44:24] [DefaultDispatcher-worker-1/WARN]: Exception in thread "DefaultDispatcher-worker-1" java.lang.NoSuchFieldError: HIDE_ADDITIONAL_TOOLTIP [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.discs.sources.file.FileDisc.getDiscItemStack(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.discs.sources.file.FileDisc.toJextDisc(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.discs.sources.file.FileSource.getDiscs(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.discs.sources.file.FileSource$getDiscs$1.invokeSuspend(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.DispatchedTask.run(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	at JEXT-Reborn_2.0.7.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source) [20:44:24] [DefaultDispatcher-worker-1/WARN]: 	Suppressed: me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@720f3021, Dispatchers.Default]

### Server Version

1.19.4

### Server Type

Purpur

### Discs.json

```json
[
  {
    "title": "Joost & DJ Klingelton",
    "author": "Europapa (Ringtone)",
    "creeper-drop": true,
    "model-data": 1,
    "disc-namespace": "joostdjklingeltoneuropaparingtoneone",
    "loot-tables": {},
    "fragment-loot-tables": {},
    "duration": 58,
    "lores": []
  }
]
```

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Fixed in latest update

**Comment by Yashero4ka** [comment]
Problem still appearing in 1.20.1 purpur

Log: https://mclo.gs/ZE8iuCs
Discs and resourcepack: https://drive.google.com/file/d/1dMEgrVqcyxlQaOBzJmCVX2zRdq22yjRM/view?usp=sharing
